##This file deploys the postgres instance to sql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql
          image: postgres
          env:
          - name: POSTGRES_PASSWORD
            value: "Sql@123456789"      
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: pgsql
