##This file deploys an azure sql instance to kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest

          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "Sql@123456789"      
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: mssql
